[tool.uv.workspace]
members = [
    "engine",
    "protocol/pyrat_base",
    "cli",
]

[tool.mypy]
python_version = "3.8"
namespace_packages = true
explicit_package_bases = true
files = ["engine/python", "protocol/pyrat_base"]
